#!/usr/bin/env python3
"""Name-discipline audit, offline, from the stored outputs.

Neither language checks predicate names, and both prompts show the same
term list (prompts.schema_block). This counts, per run and slice, the
programs that test a fact name no case in the suite supplies and the
program itself does not derive: (name, arity) absent from both the
suite's facts and the program's rule heads. Such a program can never
see that fact, whatever the case says. LRML-IR outputs are counted
after the frozen rewriter with the type-fact ablation on
(B2W_EXIST_TRANSPARENT), the reading most generous to LRML-IR, so the
rewriter's own type-fact demands are not charged to the model.

Writes harness/runs/vocab-audit.md and draft/generated-vocab.tex.
Macros: \\Inv{Opus,Haiku,Sol,Luna}{Nomo,Lrml} = programs with an
unsupplied name over both slices, original text, plain prompt.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import rescore                                   # noqa: E402
import waist_eval                                # noqa: E402
import bracket2waist                             # noqa: E402
import bracket2waist_v2                          # noqa: E402

MODELS = [('opus5', 'Opus'), ('haiku', 'Haiku'), ('sol', 'Sol'), ('luna', 'Luna')]
ARMS = [('waist', 'Nomolog', 'Nomo'), ('lrml', 'LRML-IR plain', 'Lrml'),
        ('lrml-parity', 'LRML-IR + scoring', None),
        ('lrml-stmt', 'LRML-IR statement-only', None),
        ('lrml-v2', 'LRML-IR + override', None)]


def suite_sigs(cases):
    sigs = set()
    for c in cases:
        for f in c['facts']:
            f = f.strip().rstrip('.')
            name = f.split('(')[0].strip()
            arity = f.count(',') + 1 if '(' in f else 0
            sigs.add((name, arity))
    return sigs


def program_text(run, stem):
    if run.endswith('waist'):
        p = stem + '.lp'
        return open(p).read() if os.path.exists(p) else None
    p = stem + '.ir.txt'
    if not os.path.exists(p):
        return None
    tr = (bracket2waist_v2.translate_program if run.endswith('-v2')
          else bracket2waist.translate)
    try:
        return tr(open(p).read())
    except Exception:
        return None


def unsupplied(text, sigs):
    """Set of (name, arity) tested in a body, derived nowhere, supplied by no case.
    None if the program does not parse."""
    try:
        prog = waist_eval.parse_program(text)
    except Exception:
        return None
    heads = {(h[0], len(h[1])) for h, _, _, _ in prog['rules']}
    bad = set()
    for _, body, _, _ in prog['rules']:
        for lit in body:
            if lit[0] in ('pos', 'neg'):
                sig = (lit[1], len(lit[2]))
                if sig not in heads and sig not in sigs:
                    bad.add(sig)
    return bad


def main():
    bracket2waist.ABLATE_EXIST = True
    rows, macros = [], []
    for mkey, mname in MODELS:
        for akey, aname, mac in ARMS:
            run = f'e2-{mkey}-{akey}'
            if not os.path.isdir(os.path.join(HERE, 'runs', run)):
                continue
            per = {}
            for sl in ('comparability', 'exception'):
                n = unp = inv = 0
                for _, cases, stem in rescore.iter_items(run, sl):
                    n += 1
                    t = program_text(run, stem)
                    b = unsupplied(t, suite_sigs(cases)) if t else None
                    if b is None:
                        unp += 1
                    elif b:
                        inv += 1
                per[sl] = (n, unp, inv)
            n = sum(v[0] for v in per.values())
            unp = sum(v[1] for v in per.values())
            inv = sum(v[2] for v in per.values())
            rows.append(f'| {run} ({mname}, {aname}) | {n - unp}/{n} | '
                        f'{per["comparability"][2]} | {per["exception"][2]} | {inv} |')
            if mac:
                macros.append(f'\\newcommand{{\\Inv{mname}{mac}}}{{{inv}}}')
    bracket2waist.ABLATE_EXIST = False
    md = ['# Name-discipline audit (regenerated by harness/audit_vocab.py)', '',
          'Programs that test a fact name no case supplies and the program does not',
          'derive, over the stored outputs, original text. Neither language checks',
          'names; both prompts list the suite\'s terms. LRML-IR is counted after the',
          'frozen rewriter with type facts ignored (most generous to LRML-IR).', '',
          '| run | parsed | single sentences | exception passages | total |',
          '|---|---|---|---|---|'] + rows + ['']
    with open(os.path.join(HERE, 'runs', 'vocab-audit.md'), 'w') as f:
        f.write('\n'.join(md))
    with open(os.path.join(HERE, '..', 'draft', 'generated-vocab.tex'), 'w') as f:
        f.write('% generated by harness/audit_vocab.py; do not edit\n'
                + '\n'.join(macros) + '\n')
    print('\n'.join(md))
    print('\n'.join(macros))


if __name__ == '__main__':
    main()
