"""Runtime-reject audit over the STORED runs (no API calls).

A *runtime reject* is the scorer's `runtime_reject` failure mode
(run_e2.score): the translated program parsed and passed the safety check,
but the evaluator raised on at least one case (e.g. an ordered comparison
whose operand is a bare constant rather than a number). Every such suite
scores 0 of its cases under the frozen primary.

For every run this script reports, per output (n=142: 71 sentences x
original/reworded):
  parse-fail      the model never produced a well-formed IR/program
                  (failure_mode = parse_failure);
  translate-fail  translator raised (failure_mode = translate_error; by
                  policy P3 this never happens on well-formed input);
  runtime-reject  as above;
  scored          every case evaluated (exact suites in parentheses).
For the plain-grammar LRML-IR runs it also re-translates each rejected IR
through the corrected translator v1.1 (bracket2waist_v11) and counts how
many become fully evaluable, and how many of those pass their suite.

Writes harness/runs/runtime-rejects-audit.md (table) and
draft/generated-rejects.tex (macros used by the paper). Usage:
    python3 harness/audit_runtime_rejects.py   (from papers/jurix-compilation)
"""
import collections
import csv
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import bracket2waist_v11                                # noqa: E402
import safety                                           # noqa: E402
import waist_eval                                       # noqa: E402

SLICES = {'comparability': 'gold', 'exception': 'gold-exception'}
MODELS = [('opus5', 'Opus 5'), ('haiku', 'Haiku 4.5'),
          ('sol', 'Sol'), ('luna', 'Luna')]
ARMS = [('lrml', 'LRML-IR plain'), ('lrml-parity', 'LRML-IR informed'),
        ('lrml-stmt', 'LRML-IR statement-only'),
        ('lrml-v2', 'LRML-IR+override'), ('lrml-taught', 'LRML-IR taught'),
        ('waist', 'Nomolog')]
V1_GRAMMAR = {'lrml', 'lrml-parity', 'lrml-stmt', 'lrml-taught'}
MACRO_KEY = {('opus5', 'lrml'): 'Opus', ('haiku', 'lrml'): 'Haiku',
             ('sol', 'lrml'): 'Sol', ('luna', 'lrml'): 'Luna',
             ('sol', 'lrml-v2'): 'SolOvr', ('haiku', 'lrml-v2'): 'HaikuOvr',
             ('luna', 'lrml-v2'): 'LunaOvr'}


def cases_for(sl, cand):
    return json.load(open(os.path.join(BASE, SLICES[sl], cand,
                                       'cases.json')))['cases']


def run_cases(prog_text, cases):
    """-> (n_raised, error_messages, n_passed)."""
    try:
        prog = waist_eval.parse_program(prog_text)
        safety.safety_check(prog)
    except waist_eval.FragmentError as e:
        return len(cases), [f'unparseable: {e}'], 0
    raised, errs, passed = 0, [], 0
    for c in cases:
        facts = [waist_eval.parse_atom(f.rstrip('.').strip())
                 for f in c['facts']]
        try:
            a, v = waist_eval.verdict(prog, facts)
        except (waist_eval.FragmentError, KeyError, RecursionError) as e:
            raised += 1
            errs.append(str(e))
            continue
        passed += (a == c['expect']['applies']
                   and v == c['expect']['violation'])
    return raised, errs, passed


def classify(msg):
    if 'ordered comparison over non-numbers' in msg:
        return 'comparison over a bare constant'
    if 'unsafe' in msg:
        return 'unsafe rule'
    if 'stratif' in msg or 'circular' in msg or 'cycle' in msg:
        return 'circular defeat / stratification'
    return 'other: ' + msg[:60]


def main():
    lines = ['# Runtime-reject audit (regenerated by '
             'harness/audit_runtime_rejects.py)', '',
             'Status vocabulary is run_e2.score\'s `failure_mode`; see the '
             'script docstring. n=142 outputs per run (71 sentences x '
             'original/reworded) except the taught run (20 exception '
             'originals).', '',
             '| run | parse-fail | translate-fail | runtime-reject '
             '(comp/exc) | scored (exact) | v1.1 evaluable | v1.1 exact |',
             '|---|---|---|---|---|---|---|']
    macros = ['% AUTO-GENERATED by harness/audit_runtime_rejects.py '
              '— do not edit.']
    kinds = collections.Counter()
    for model, mlabel in MODELS:
        for arm, alabel in ARMS:
            run = f'e2-{model}-{arm}'
            path = os.path.join(HERE, 'runs', run, 'results.csv')
            if not os.path.exists(path):
                continue
            rows = list(csv.DictReader(open(path)))
            modes = collections.Counter(r['failure_mode'] for r in rows)
            n_parse = modes.get('parse_failure', 0)
            n_trans = modes.get('translate_error', 0)
            n_rej = modes.get('runtime_reject', 0)
            n_scored = len(rows) - n_parse - n_trans - n_rej
            n_exact = sum(r['suite_exact'] == '1' for r in rows)
            rej_rows = [r for r in rows if r['failure_mode'] ==
                        'runtime_reject']
            rej_by_slice = collections.Counter(r['slice'] for r in rej_rows)
            # re-run the stored translated program to classify the error
            v11_eval = v11_exact = 0
            for r in rej_rows:
                stem = os.path.join(HERE, 'runs', run, 'out',
                                    f"{r['slice']}-{r['example_id']}-"
                                    f"{r['variant']}")
                cases = cases_for(r['slice'], r['example_id'])
                if os.path.exists(stem + '.lp'):
                    _, errs, _ = run_cases(open(stem + '.lp').read(), cases)
                    for e in errs:
                        kinds[(run, classify(e))] += 1
                if arm in V1_GRAMMAR and os.path.exists(stem + '.ir.txt'):
                    try:
                        prog = bracket2waist_v11.translate(
                            open(stem + '.ir.txt').read())
                        raised, _, passed = run_cases(prog, cases)
                    except Exception:
                        raised, passed = len(cases), 0
                    if raised == 0:
                        v11_eval += 1
                        v11_exact += passed == len(cases)
            v11 = ('n/a (v2 grammar)' if arm == 'lrml-v2' else
                   f'{v11_eval}' if arm in V1_GRAMMAR else '—')
            v11x = (f'{v11_exact}' if arm in V1_GRAMMAR and n_rej else
                    '—' if arm not in V1_GRAMMAR else '0')
            lines.append(
                f'| {run} ({mlabel}, {alabel}) | {n_parse} | {n_trans} | '
                f'{n_rej} ({rej_by_slice.get("comparability", 0)}/'
                f'{rej_by_slice.get("exception", 0)}) | {n_scored} '
                f'({n_exact}) | {v11} | {v11x} |')
            key = MACRO_KEY.get((model, arm))
            if key:
                macros.append(f'\\newcommand{{\\Rej{key}}}{{{n_rej}}}')
                if arm in V1_GRAMMAR:
                    macros.append(
                        f'\\newcommand{{\\RejVxi{key}}}{{{v11_eval}}}')
                    macros.append(
                        f'\\newcommand{{\\RejVxiEx{key}}}{{{v11_exact}}}')
    lines += ['', '## Error kinds behind the rejects (per case, re-run over '
              'the stored translated programs)', '',
              '| run | kind | cases |', '|---|---|---|']
    for (run, kind), n in sorted(kinds.items()):
        lines.append(f'| {run} | {kind} | {n} |')
    lines += ['', '## Summary', '',
              '1. Every runtime reject in every run is the same evaluator '
              'error: an ordered comparison whose operand is a bare constant '
              '(the model wrote `greater than equal( height, 900 mm)` with '
              '`height` as a bare entity instead of an attribute); the frozen '
              'v1 translator renders bare all-alpha operands as constants, '
              'and the evaluator refuses to order a constant against a '
              'number. Opus never writes this; the other three models do.',
              '2. These are not policy-P3 violations: P3 (totality) requires '
              'every well-formed IR to translate, and it does; the programs '
              'parse and pass the safety check, and the reject happens in '
              'the evaluator. The v1.1 addendum\'s "translator bug by P3" '
              'clause covers safety/stratification failures of v1.1\'s own '
              'output, which never occur here.',
              '3. They are, however, the M2c defect (F3 in the v1.1 ledger: '
              'bare entity operands as dead constants), so the corrected '
              'translator is the right upper bound: the "v1.1 evaluable" '
              'column counts rejected IRs that evaluate on every case under '
              'v1.1, and "v1.1 exact" how many of those then pass their '
              'suite.',
              '4. The paper\'s best-of-four upper bound (Table 2) is Opus '
              'only, and Opus has no rejects in the plain run; for the other '
              'models the rejects are absorbed only where the paper reports '
              'v1.1 numbers (Haiku plain). The override runs use the v2 '
              'grammar, to which v1.1 does not apply.',
              '5. Under the frozen primary a rejected suite scores 0 of its '
              'cases, so the rejects depress the non-Opus LRML-IR case-level '
              'numbers and cannot change the exact-suite ordering (a '
              'rejected suite is already a failed suite).']
    with open(os.path.join(HERE, 'runs', 'runtime-rejects-audit.md'),
              'w') as f:
        f.write('\n'.join(lines) + '\n')
    os.makedirs(os.path.join(BASE, 'draft'), exist_ok=True)
    with open(os.path.join(BASE, 'draft', 'generated-rejects.tex'), 'w') as f:
        f.write('\n'.join(macros) + '\n')
    print('\n'.join(lines))
    print('\n'.join(macros))


if __name__ == '__main__':
    main()
