"""Generate draft/generated.tex from the scored runs — the paper's numbers
stay reproducible from results.csv (KT's rerun regenerates them). Stdlib only.

Usage: python3 harness/gen_tex.py   (from papers/jurix-compilation)
"""
import csv
import os

RUNS = {
    ('opus', 'waist'): 'e2-opus5-waist',
    ('opus', 'lrml'): 'e2-opus5-lrml',
    ('opus', 'lrmlOvr'): 'e2-opus5-lrml-v2',
    ('opus', 'lrmlPar'): 'e2-opus5-lrml-parity',
    ('haiku', 'waist'): 'e2-haiku-waist',
    ('haiku', 'lrml'): 'e2-haiku-lrml',
    ('haiku', 'lrmlOvr'): 'e2-haiku-lrml-v2',
    ('haiku', 'lrmlPar'): 'e2-haiku-lrml-parity',
    ('opus', 'lrmlStmt'): 'e2-opus5-lrml-stmt',
    ('haiku', 'lrmlStmt'): 'e2-haiku-lrml-stmt',
    ('sol', 'lrmlStmt'): 'e2-sol-lrml-stmt',
    ('luna', 'lrmlStmt'): 'e2-luna-lrml-stmt',
    ('sol', 'waist'): 'e2-sol-waist',
    ('sol', 'lrml'): 'e2-sol-lrml',
    ('sol', 'lrmlPar'): 'e2-sol-lrml-parity',
    ('sol', 'lrmlOvr'): 'e2-sol-lrml-v2',
    ('luna', 'waist'): 'e2-luna-waist',
    ('luna', 'lrml'): 'e2-luna-lrml',
    ('luna', 'lrmlPar'): 'e2-luna-lrml-parity',
    ('luna', 'lrmlOvr'): 'e2-luna-lrml-v2',
}
HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.dirname(HERE)


def agg(rows):
    total = sum(int(r['cases_total']) for r in rows)
    passed = sum(int(r['cases_passed']) for r in rows)
    exact = sum(int(r['suite_exact']) for r in rows)
    return exact / len(rows), passed / max(1, total), exact, len(rows)


def _binom_cdf(k, n, p):
    from math import comb
    return sum(comb(n, i) * p**i * (1 - p)**(n - i) for i in range(k + 1))


def clopper_pearson(k, n, alpha=0.05):
    """Exact binomial CI via bisection; stdlib only."""
    def bisect(f, lo, hi):
        for _ in range(60):
            mid = (lo + hi) / 2
            if f(mid):
                hi = mid
            else:
                lo = mid
        return (lo + hi) / 2
    lo = 0.0 if k == 0 else bisect(
        lambda p: 1 - _binom_cdf(k - 1, n, p) > alpha / 2, 0, k / n)
    hi = 1.0 if k == n else bisect(
        lambda p: _binom_cdf(k, n, p) < alpha / 2, k / n, 1)
    return lo, hi


def main():
    cells = {}
    for (model, arm), run in RUNS.items():
        with open(os.path.join(HERE, 'runs', run, 'results.csv')) as f:
            rows = list(csv.DictReader(f))
        for sl in ('comparability', 'exception'):
            for var in ('original', 'perturbed'):
                sel = [r for r in rows if r['slice'] == sl
                       and r['variant'] == var]
                cells[(model, arm, sl, var)] = agg(sel)

    def macro(name, value):
        return f'\\newcommand{{\\{name}}}{{{value}}}\n'

    def pct(x):
        return f'{100 * x:.0f}\\%'

    out = ['% AUTO-GENERATED by harness/gen_tex.py from scored runs — do not edit.\n']
    out.append(macro('nComp', 60))
    out.append(macro('nCompGold', 51))
    out.append(macro('nStrata', 9))
    out.append(macro('nExc', 20))
    import json as _json
    n_cases = 0
    for root in ('gold', 'gold-exception'):
        rootp = os.path.join(BASE, root)
        for d in os.listdir(rootp):
            cp = os.path.join(rootp, d, 'cases.json')
            if os.path.isfile(cp):
                n_cases += len(_json.load(open(cp))['cases'])
    out.append(macro('nCases', n_cases))
    out.append('\\newcommand{\\resultPlaceholder}[1]{\\textbf{[#1: pending]}}\n')
    ci_lines = ['# Exact binomial (Clopper–Pearson) 95% CIs on exact-suite '
                'proportions\n',
                '| model | arm | slice | variant | k/n | CI |', '|' + '---|' * 6]
    for (model, arm, sl, var), (ex, acc, k, n) in sorted(cells.items()):
        key = (model.capitalize() + arm.capitalize()
               + sl[:4].capitalize() + var[:4].capitalize())
        out.append(macro(key + 'Ex', pct(ex)))
        out.append(macro(key + 'Acc', pct(acc)))
        lo, hi = clopper_pearson(k, n)
        out.append(macro(key + 'ExCI',
                         f'[{100 * lo:.0f}\\%,\\,{100 * hi:.0f}\\%]'))
        ci_lines.append(f'| {model} | {arm} | {sl} | {var} | {k}/{n} | '
                        f'[{100 * lo:.1f}%, {100 * hi:.1f}%] |')
    with open(os.path.join(HERE, 'runs', 'CIS.md'), 'w') as f:
        f.write('\n'.join(ci_lines) + '\n\nRegenerate: python3 '
                'harness/gen_tex.py (auto-written alongside generated.tex)\n')
    # paired exact sign tests: waist vs flat IR on identical
    # sentences, suite_exact, original variants
    from math import comb
    def sign_test(b, c):
        n = b + c
        if n == 0:
            return 1.0
        k = min(b, c)
        tail = sum(comb(n, i) for i in range(k + 1)) / 2**n
        return min(1.0, 2 * tail)
    def fmt_p(p):
        return 'p<0.001' if p < 0.001 else f'p={p:.3f}'.rstrip('0').rstrip('.')
    for model in ('opus', 'haiku', 'sol', 'luna'):
        rows_w = list(csv.DictReader(open(os.path.join(
            HERE, 'runs', RUNS[(model, 'waist')], 'results.csv'))))
        rows_l = list(csv.DictReader(open(os.path.join(
            HERE, 'runs', RUNS[(model, 'lrml')], 'results.csv'))))
        for sl in ('comparability', 'exception'):
            def exacts(rows):
                return {r['example_id']: r['suite_exact'] == '1'
                        for r in rows if r['slice'] == sl
                        and r['variant'] == 'original'}
            w, l = exacts(rows_w), exacts(rows_l)
            b = sum(1 for k in w if w[k] and not l.get(k, False))
            c = sum(1 for k in w if not w[k] and l.get(k, False))
            key = model.capitalize() + sl[:4].capitalize()
            out.append(macro(f'Disc{key}', f'{b}~vs.~{c}'))
            out.append(macro(f'PairP{key}', fmt_p(sign_test(b, c))))
    # headline deltas (exact-suite, original)
    for model in ('opus', 'haiku'):
        for sl in ('comparability', 'exception'):
            d = (cells[(model, 'waist', sl, 'original')][0]
                 - cells[(model, 'lrml', sl, 'original')][0])
            out.append(macro(f'delta{model.capitalize()}{sl[:4].capitalize()}',
                             f'{100 * d:+.0f}'))
    # draft/ is absent in the public companion export; create it so the
    # advertised one-command check works from a fresh clone.
    os.makedirs(os.path.join(BASE, 'draft'), exist_ok=True)
    path = os.path.join(BASE, 'draft', 'generated.tex')
    with open(path, 'w') as f:
        f.write(''.join(out))
    print(f'wrote {path} ({len(cells)} cells)')


if __name__ == '__main__':
    main()
